clear all 
clc
%Generate data samples from 3 1-D Gaussians, with different means and variances. (You
%can generate 50 samples from each distribution using mvnrnd function)
mean1 = 0;  
mean2 = 6;
mean3 = 10;
vari1 = .5;
vari2 = 2;
vari3 = 4;

%Generate random sampls fro parameters
samp1 = mvnrnd(mean1,vari1,1000);
samp2 = mvnrnd(mean2,vari2,1000);
samp3 = mvnrnd(mean3,vari3,1000);

%Plotting pdf from mean/var we picked
x = [-5:.1:20];
norm1 = normpdf(x,mean1,(vari1)^.5);
plot(x,norm1,'c','LineWidth',2)
norm2 = normpdf(x,mean2,(vari2)^.5);
hold on
plot(x,norm2,'m','LineWidth',2)
norm3 = normpdf(x,mean3,(vari3)^.5);
plot(x,norm3,'g','LineWidth',2)
title('Gaussians given mean and var')
ylim([0 1])


%Try to recover the model parameters used in previous part, using the samples generated.
D = [samp1 ;samp2 ;samp3];%All sample data points in ONE column, for 1D
GMModel = fitgmdist(D,3)%Find a model, 3 components, D hs only 1 column so it is 1 dimensionsal, it will find 3 1D gassians
meanFound = GMModel.mu;
varFound = [GMModel.Sigma(1) GMModel.Sigma(2) GMModel.Sigma(3)];
gmm1 = normpdf(x,meanFound(1),varFound(1)^.5);
gmm2 = normpdf(x,meanFound(2),varFound(2)^.5);
gmm3 = normpdf(x,meanFound(3),varFound(3)^.5);
figure
plot(x,gmm1,'LineWidth',2)
hold on
plot(x,gmm2,'LineWidth',2)
plot(x,gmm3,'LineWidth',2)
title('Gaussians found using GMM')
ylim([0 1])



%Try to recover the model parameters for 4 Gaussians (means and variances
%of 4 Gaussians that fit the data generated by 3 in step 1. Discuss what you observe.
Fit4 = fitgmdist(D,4);
Fit4mean = Fit4.mu;
Fit4var = [Fit4.Sigma(1) Fit4.Sigma(2) Fit4.Sigma(3) Fit4.Sigma(4)];
Fit4gmm1 = normpdf(x,Fit4mean(1),Fit4var(1)^.5);
Fit4gmm2 = normpdf(x,Fit4mean(2),Fit4var(2)^.5);
Fit4gmm3 = normpdf(x,Fit4mean(3),Fit4var(3)^.5);
Fit4gmm4 = normpdf(x,Fit4mean(4),Fit4var(4)^.5);
figure
plot(x,Fit4gmm1,'LineWidth',2)
hold on
plot(x,Fit4gmm2,'LineWidth',2)
plot(x,Fit4gmm3,'LineWidth',2)
plot(x,Fit4gmm4,'LineWIdth',2)
title('Fitting 4 Gaussians to sample data from 3')
ylim([0 1])





